'use strict';

export const ENTRIES_REQUEST = 'ENTRIES_REQUEST';
export const ENTRIES_REQUEST_SUCCESS = 'ENTRIES_REQUEST_SUCCESS';
export const ENTRIES_REQUEST_FAIL = 'ENTRIES_REQUEST_FAIL';

export const SESSION_REQUEST = 'SESSION_REQUEST';
export const SESSION_REQUEST_SUCCESS = 'SESSION_REQUEST_SUCCESS';
export const SESSION_REQUEST_FAIL = 'SESSION_REQUEST_FAIL';
