'use strict';

export const ENTRIES_REQUEST = 'ENTRIES_REQUEST';
export const ENTRIES_REQUEST_SUCCESS = 'ENTRIES_REQUEST_SUCCESS';
export const ENTRIES_REQUEST_FAIL = 'ENTRIES_REQUEST_FAIL';

export const ENTRY_DETAIL_REQUEST = 'ENTRY_DETAIL_REQUEST';
export const ENTRY_DETAIL_REQUEST_SUCCESS = 'ENTRY_DETAIL_REQUEST_SUCCESS';
export const ENTRY_DETAIL_REQUEST_FAIL = 'ENTRY_DETAIL_REQUEST_FAIL';

export const SESSION_CREATE = 'SESSION_CREATE';
export const SESSION_CREATE_SUCCESS = 'SESSION_CREATE_SUCCESS';
export const SESSION_CREATE_FAIL = 'SESSION_CREATE_FAIL';
export const SESSION_DESTROY = 'SESSION_DESTROY';
export const SESSION_DESTROY_SUCCESS = 'SESSION_DESTROY_SUCCESS';
export const SESSION_DESTROY_FAIL = 'SESSION_DESTROY_FAIL';
